website:
  announcement:
    dismissable: false
    content: "Pre-release Documentation"
  navbar:
    pinned: true

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss, theme-prerelease-docs.scss]
