# Pre-release version number
version: v1.5

website:
  title: "Quarto (Pre-release)"
  google-analytics: "G-FV9Z7SDZ0M"
  image: "quarto-dark-bg-pre.jpeg"
  site-url: https://prerelease.quarto.org
  repo-url: https://github.com/quarto-dev/quarto-web/tree/prerelease
  announcement:
    dismissable: false
    content: "Pre-release ({{< meta version >}}) Documentation: [Download {{< meta version >}}](/docs/download/prerelease.qmd), [Current Release Docs](http://quarto.org) "
  navbar:
    pinned: true

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss, theme-prerelease-docs.scss]
