# Pre-release version number
version: v1.5

website:
  announcement:
    dismissable: false
    content: "Pre-release ({{< meta version >}}) Documentation: [Download {{< meta version >}}](/docs/download/prerelease.qmd), [Current Release Docs](http://quarto.org) "
  navbar:
    pinned: true

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss, theme-prerelease-docs.scss]
