name: Port change to prerelease
on:
  pull_request_target:
    types: [closed]

permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests

jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    # Don't run on closed unmerged pull requests and only PRs to main
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'
    steps:
      - uses: actions/checkout@v4
      - name: Create backport pull requests
        # https://github.com/korthout/backport-action/releases/tag/v3.0.0
        uses: korthout/backport-action@7e7cb1977d64d20339e8fdec12c0a1a065371de7
        with:
          cherry_picking: auto
          branch_name: sync-${pull_number}-to-${target_branch}
          merge_commits: skip
          pull_description: |
            # Description
            Sync of #${pull_number} to `${target_branch}`.

            ## Original PR

            ### ${pull_title}
            ${pull_description}
          # Don't trigger on labels, and always PR to prerelease
          label_pattern: ''
          target_branches: prerelease